owner: fairdataihub
repo: uptime

sites:
  - name: Organization Website
    url: https://fairdataihub.org
    assignees:
      - megasanjay
  - name: SODA for SPARC Documentation
    url: https://docs.sodaforsparc.io
    assignees:
      - aaronm-2112
  - name: FAIRshare Documentation
    url: https://docs.fairshareapp.io
    assignees:
      - megasanjay
  - name: Developer Documentation
    url: https://dev.fairdataihub.org
    assignees:
      - megasanjay
  - name: AI-READI Website
    url: https://aireadi.org
    assignees:
      - megasanjay
  - name: FAIRshare Authentication
    url: https://auth.fairshareapp.io
    assignees:
      - megasanjay
  - name: Upload Website
    url: https://upload.fairdataihub.org
    assignees:
      - megasanjay
  - name: SPARClink
    url: https://sparclink.vercel.app
    assignees:
      - megasanjay
  - name: Open Graph Image Generation Studio
    url: https://kalai.fairdataihub.org
    assignees:
      - megasanjay
  - name: Umami
    url: https://umami.fairdataihub.org
    assignees:
      - megasanjay
  - name: Alt Text Generator for Images
    url: https://alt.fairdataihub.org
    assignees:
      - megasanjay
  - name: Status Page
    url: https://status.fairdataihub.org
    assignees:
      - megasanjay
      
commitMessages:
  commitAuthorName: "fairdataihub-bot"
  commitAuthorEmail: "fairdataihub@gmail.com"

status-website:
  name: "System Status"

  cname: status.fairdataihub.org

  introTitle: "**Health Dashboard** for FAIR Data Innovations Hub"
  introMessage: We continuously monitor our applications and all its services. If there are any service interruptions, scheduled maintenances or downtimes, an update will be posted here.

  logoUrl: https://fairdataihub.org/smalllogo.svg

  favicon: https://fairdataihub.org/favicon.ico
  faviconSvg: https://fairdataihub.org/smalllogo.svg

  themeUrl: https://fairdataihub.org/css/custom-uptime.css

  metaTags:
    - name: "robots"
      content: "noindex"

  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER
    - title: FAIR Data Innovations Hub
      href: https://fairdataihub.org
